local:
  key_vault_uri: "https://devdatext8wukv0.vault.azure.net/"
  tenant_id: "16b3c013-d300-468d-ac64-7eda0820b6d3"
  user_managed_identity:
    client_id:
      value: "149bef02-1ac5-4d8f-b496-7dead98a3d28"
  cosmosdb:
    db_name:
      value: "data-extraction-db"
    endpoint:
      key: "cosmosdb-connection-string"
      type: "secret"
    configuration_collection_name:
      value: "Configurations"
    document_collection_name:
      value: "Documents"
  llm:
    model_name:
      value: "gpt-4o"
    endpoint:
      value: "https://azure-cognitive-o4twr.openai.azure.com/openai/deployments/gpt-4o"
    access_key:
      key: "open-ai-key"
      type: "secret"
    api_version:
      value: "2025-04-01-preview"
  content_understanding:
    endpoint:
      value: "https://devdatext8wuais0-cog-s36e.cognitiveservices.azure.com/"
    subscription_key:
      key: "ai-foundry-key"
      type: "secret"
    request_timeout:
      value: 30
    project_id:
      value: "devdatext8Wu-rag-project-p029lx"
  default_ingest_config:
    name:
      value: document-extraction
    version:
      value: v1.0
  chat_history:
    endpoint:
      value: "https://devdatext8wucosmoskb0.documents.azure.com:443/"
    db_name:
      value: "knowledge-base-db"
    chat_history_container_name:
      value: "chat-history"
    user_message_limit:
      value: 20
    domain:
      value: "Data Extraction AI"
  blob_storage:
    account_url:
      value: "https://devdatext8wusa0.blob.core.windows.net/"
    container_name:
      value: "rawdocuments"


dev:
  key_vault_uri: "https://devdatext8wukv0.vault.azure.net/"
  tenant_id: "16b3c013-d300-468d-ac64-7eda0820b6d3"
  user_managed_identity:
    client_id:
      value: "149bef02-1ac5-4d8f-b496-7dead98a3d28"
  cosmosdb:
    db_name:
      value: "data-extraction-db"
    endpoint:
      key: "cosmosdb-connection-string"
      type: "secret"
    configuration_collection_name:
      value: "Configurations"
    document_collection_name:
      value: "Documents"
  llm:
    model_name:
      value: "gpt-4o"
    endpoint:
      value: "https://azure-cognitive-o4twr.openai.azure.com/openai/deployments/gpt-4o"
    access_key:
      key: "open-ai-key"
      type: "secret"
    api_version:
      value: "2025-04-01-preview"
  content_understanding:
    endpoint:
      value: "https://devdatext8wuais0-cog-s36e.cognitiveservices.azure.com/"
    subscription_key:
      key: "ai-foundry-key"
      type: "secret"
    request_timeout:
      value: 30
    project_id:
      value: "devdatext8Wu-rag-project-p029lx"
  default_ingest_config:
    name:
      value: document-extraction
    version:
      value: v1.0
  chat_history:
    endpoint:
      value: "https://devdatext8wucosmoskb0.documents.azure.com:443/"
    db_name:
      value: "knowledge-base-db"
    chat_history_container_name:
      value: "chat-history"
    user_message_limit:
      value: 20
    domain:
      value: "Data Extraction AI"
  blob_storage:
    account_url:
      value: "https://devdatext8wusa0.blob.core.windows.net/"
    container_name:
      value: "raw_documents"


# TODO: Update later
# uat:
#   user_managed_identity_client_id: ""
#   ...
#
# prod:
#   user_managed_identity_client_id: ""
#   ...
