version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    level: DEBUG

loggers:
  # Root logger
  '':
    level: WARNING
    handlers: [console]

  # Application logger
  __main__:
    level: INFO
    handlers: [console]
    propagate: False

  services:
    level: INFO
    handlers: [console]
    propagate: False

  config:
    level: INFO
    handlers: [console]
    propagate: False

  utils:
    level: INFO
    handlers: [console]
    propagate: False

root:
  level: WARNING
  handlers: [console]
